### ISSUE TITLE
Allow external configuration of the iiif player component

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/react-iiif-media-player#1]
### Description
We need to allow external configuration of the iiif player component which users can import into their applications.   For example, if you need to use credentials in a `fetch` operation to grab the supplied iiif manifest url for security, this should be configurable and not a hard-wired setting.

### Done Looks Like
When importing this react component into your project, you can optionally pass a config object as a prop to the component.

For example:
```
<IIIFMediaPlayer config={ fetch: { credentials: 'include' } } />
```

### Tasks
- [x] Create an additional Redux reducer to hold configuration
- [x] Add support for configuration in the component application
- [x] Allow for all cases where config is passed in or not
- [x] Update tests

**Comment by adamjarling** [comment]
@mcwhitaker @davidschober @joncameron @cjcolvar  Pulling this in also, to fix a previous config change Chris needs for avalon-bundle
